#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments
#------------------------------------------------------------------------------

# wmake $targetType ../ADMno1
# wmake $targetType admInterfaceProperties
wmake $targetType ../ADMno1Multiphase
wmake $targetType admMixture
wmake $targetType

#------------------------------------------------------------------------------
