#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory
#------------------------------------------------------------------------------

# wclean libso ../ADMno1
# wclean libso admInterfaceProperties
wclean libso ../ADMno1Multiphase
wclean libso admMixture
wclean

#------------------------------------------------------------------------------
